import { TemporalFailure } from './failure';
/**
 * Thrown from code that receives a value that is unexpected or that it's unable to handle.
 */
export declare class ValueError extends Error {
    readonly cause?: unknown;
    constructor(message: string | undefined, cause?: unknown);
}
/**
 * Thrown when a Payload Converter is misconfigured.
 */
export declare class PayloadConverterError extends ValueError {
}
/**
 * Used in different parts of the SDK to note that something unexpected has happened.
 */
export declare class IllegalStateError extends Error {
}
/**
 * This exception is thrown in the following cases:
 *  - Workflow with the same Workflow Id is currently running
 *  - There is a closed Workflow with the same Workflow Id and the {@link WorkflowOptions.workflowIdReusePolicy}
 *    is `WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE`
 *  - There is closed Workflow in the `Completed` state with the same Workflow Id and the {@link WorkflowOptions.workflowIdReusePolicy}
 *    is `WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY`
 */
export declare class WorkflowExecutionAlreadyStartedError extends TemporalFailure {
    readonly workflowId: string;
    readonly workflowType: string;
    constructor(message: string, workflowId: string, workflowType: string);
}
/**
 * Thrown when a Workflow with the given Id is not known to Temporal Server.
 * It could be because:
 * - Id passed is incorrect
 * - Workflow is closed (for some calls, e.g. `terminate`)
 * - Workflow was deleted from the Server after reaching its retention limit
 */
export declare class WorkflowNotFoundError extends Error {
    readonly workflowId: string;
    readonly runId: string | undefined;
    constructor(message: string, workflowId: string, runId: string | undefined);
}
/**
 * Thrown when the specified namespace is not known to Temporal Server.
 */
export declare class NamespaceNotFoundError extends Error {
    readonly namespace: string;
    constructor(namespace: string);
}
